// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TransitPay.API.Data;

#nullable disable

namespace TransitPay.API.Migrations
{
    [DbContext(typeof(TransitPayDbContext))]
    [Migration("20260810022841_MakeRowVersionNullable")]
    partial class MakeRowVersionNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TransitPay.API.Models.AuthAuditLog", b =>
                {
                    b.Property<long>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("audit_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AuditId"));

                    b.Property<string>("ActorHash")
                        .HasColumnType("text")
                        .HasColumnName("actor_hash");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("AuditId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EventType");

                    b.HasIndex("UserId");

                    b.ToTable("auth_audit_logs", (string)null);
                });

            modelBuilder.Entity("TransitPay.API.Models.Card", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("card_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CardId"));

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("card_number");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiry_date");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issue_date");

                    b.Property<int>("PassengerType")
                        .HasColumnType("integer")
                        .HasColumnName("passenger_type");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("CardId");

                    b.HasIndex("CardNumber")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("cards", (string)null);
                });

            modelBuilder.Entity("TransitPay.API.Models.DiscountApplication", b =>
                {
                    b.Property<int>("DiscountApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("discount_application_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DiscountApplicationId"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("integer")
                        .HasColumnName("approved_by");

                    b.Property<int>("CardId")
                        .HasColumnType("integer")
                        .HasColumnName("card_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DiscountDocument")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("discount_document");

                    b.Property<int?>("DiscountProgramId")
                        .HasColumnType("integer")
                        .HasColumnName("discount_program_id");

                    b.Property<int>("DiscountTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("discount_type_id");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rejected_at");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rejection_reason");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("DiscountApplicationId");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("CardId");

                    b.HasIndex("DiscountProgramId");

                    b.HasIndex("DiscountTypeId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("discount_applications", (string)null);
                });

            modelBuilder.Entity("TransitPay.API.Models.DiscountProgram", b =>
                {
                    b.Property<int>("DiscountProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("discount_program_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DiscountProgramId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("discount_percentage");

                    b.Property<int?>("DiscountTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("discount_type_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_approval");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("DiscountProgramId");

                    b.HasIndex("DiscountTypeId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("name IS NOT NULL AND name <> ''");

                    b.ToTable("discount_programs", null, t =>
                        {
                            t.HasCheckConstraint("CK_discount_programs_discount_percentage_range", "\"discount_percentage\" >= 0 AND \"discount_percentage\" <= 100");
                        });
                });

            modelBuilder.Entity("TransitPay.API.Models.DiscountType", b =>
                {
                    b.Property<int>("DiscountTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("discount_type_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DiscountTypeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("discount_percentage");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_approval");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("DiscountTypeId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("name IS NOT NULL AND name <> ''");

                    b.ToTable("discount_types", null, t =>
                        {
                            t.HasCheckConstraint("CK_discount_types_discount_percentage_range", "\"discount_percentage\" >= 0 AND \"discount_percentage\" <= 100");
                        });
                });

            modelBuilder.Entity("TransitPay.API.Models.FareRule", b =>
                {
                    b.Property<int>("FareId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("fare_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FareId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("DestinationTerminalId")
                        .HasColumnType("integer")
                        .HasColumnName("destination_terminal_id");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_date");

                    b.Property<decimal>("FareAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("fare_amount");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("OriginTerminalId")
                        .HasColumnType("integer")
                        .HasColumnName("origin_terminal_id");

                    b.Property<int>("PassengerType")
                        .HasColumnType("integer")
                        .HasColumnName("passenger_type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("VehicleType")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_type");

                    b.HasKey("FareId");

                    b.HasIndex("DestinationTerminalId");

                    b.HasIndex("OriginTerminalId", "DestinationTerminalId")
                        .IsUnique()
                        .HasFilter("is_active = true AND deleted_at IS NULL");

                    b.ToTable("fare_rules", null, t =>
                        {
                            t.HasCheckConstraint("CK_fare_rules_fare_amount_non_negative", "\"fare_amount\" >= 0");
                        });
                });

            modelBuilder.Entity("TransitPay.API.Models.History.DriverDeleteHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("history_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HistoryId"));

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("operation");

                    b.Property<string>("OriginalData")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_data");

                    b.Property<int>("OriginalRecordId")
                        .HasColumnType("integer")
                        .HasColumnName("original_record_id");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("performed_at");

                    b.Property<int>("PerformedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("performed_by_user_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.HasKey("HistoryId");

                    b.HasIndex("Operation");

                    b.HasIndex("OriginalRecordId");

                    b.HasIndex("PerformedAt");

                    b.ToTable("driver_delete_history", (string)null);
                });

            modelBuilder.Entity("TransitPay.API.Models.History.DriverEditHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("history_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HistoryId"));

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("operation");

                    b.Property<string>("OriginalData")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_data");

                    b.Property<int>("OriginalRecordId")
                        .HasColumnType("integer")
                        .HasColumnName("original_record_id");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("performed_at");

                    b.Property<int>("PerformedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("performed_by_user_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.HasKey("HistoryId");

                    b.HasIndex("Operation");

                    b.HasIndex("OriginalRecordId");

                    b.HasIndex("PerformedAt");

                    b.ToTable("driver_edit_history", (string)null);
                });

            modelBuilder.Entity("TransitPay.API.Models.History.FareMatrixDeleteHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("history_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HistoryId"));

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("operation");

                    b.Property<string>("OriginalData")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_data");

                    b.Property<int>("OriginalRecordId")
                        .HasColumnType("integer")
                        .HasColumnName("original_record_id");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("performed_at");

                    b.Property<int>("PerformedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("performed_by_user_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.HasKey("HistoryId");

                    b.HasIndex("Operation");

                    b.HasIndex("OriginalRecordId");

                    b.HasIndex("PerformedAt");

                    b.ToTable("fare_matrix_delete_history", (string)null);
                });

            modelBuilder.Entity("TransitPay.API.Models.History.FareMatrixEditHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("history_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HistoryId"));

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("operation");

                    b.Property<string>("OriginalData")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_data");

                    b.Property<int>("OriginalRecordId")
                        .HasColumnType("integer")
                        .HasColumnName("original_record_id");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("performed_at");

                    b.Property<int>("PerformedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("performed_by_user_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.HasKey("HistoryId");

                    b.HasIndex("Operation");

                    b.HasIndex("OriginalRecordId");

                    b.HasIndex("PerformedAt");

                    b.ToTable("fare_matrix_edit_history", (string)null);
                });

            modelBuilder.Entity("TransitPay.API.Models.History.PassengerDeleteHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("history_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HistoryId"));

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("operation");

                    b.Property<string>("OriginalData")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_data");

                    b.Property<int>("OriginalRecordId")
                        .HasColumnType("integer")
                        .HasColumnName("original_record_id");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("performed_at");

                    b.Property<int>("PerformedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("performed_by_user_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.HasKey("HistoryId");

                    b.HasIndex("Operation");

                    b.HasIndex("OriginalRecordId");

                    b.HasIndex("PerformedAt");

                    b.ToTable("passenger_delete_history", (string)null);
                });

            modelBuilder.Entity("TransitPay.API.Models.History.PassengerEditHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("history_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HistoryId"));

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("operation");

                    b.Property<string>("OriginalData")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_data");

                    b.Property<int>("OriginalRecordId")
                        .HasColumnType("integer")
                        .HasColumnName("original_record_id");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("performed_at");

                    b.Property<int>("PerformedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("performed_by_user_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.HasKey("HistoryId");

                    b.HasIndex("Operation");

                    b.HasIndex("OriginalRecordId");

                    b.HasIndex("PerformedAt");

                    b.ToTable("passenger_edit_history", (string)null);
                });

            modelBuilder.Entity("TransitPay.API.Models.History.TerminalDeleteHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("history_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HistoryId"));

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("operation");

                    b.Property<string>("OriginalData")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_data");

                    b.Property<int>("OriginalRecordId")
                        .HasColumnType("integer")
                        .HasColumnName("original_record_id");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("performed_at");

                    b.Property<int>("PerformedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("performed_by_user_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.HasKey("HistoryId");

                    b.HasIndex("Operation");

                    b.HasIndex("OriginalRecordId");

                    b.HasIndex("PerformedAt");

                    b.ToTable("terminal_delete_history", (string)null);
                });

            modelBuilder.Entity("TransitPay.API.Models.History.TerminalEditHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("history_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HistoryId"));

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("operation");

                    b.Property<string>("OriginalData")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_data");

                    b.Property<int>("OriginalRecordId")
                        .HasColumnType("integer")
                        .HasColumnName("original_record_id");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("performed_at");

                    b.Property<int>("PerformedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("performed_by_user_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.HasKey("HistoryId");

                    b.HasIndex("Operation");

                    b.HasIndex("OriginalRecordId");

                    b.HasIndex("PerformedAt");

                    b.ToTable("terminal_edit_history", (string)null);
                });

            modelBuilder.Entity("TransitPay.API.Models.PassengerDiscount", b =>
                {
                    b.Property<int>("PassengerDiscountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("passenger_discount_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PassengerDiscountId"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("integer")
                        .HasColumnName("approved_by");

                    b.Property<int>("CardId")
                        .HasColumnType("integer")
                        .HasColumnName("card_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("discount_percentage");

                    b.Property<int?>("DiscountProgramId")
                        .HasColumnType("integer")
                        .HasColumnName("discount_program_id");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("PassengerDiscountId");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("CardId")
                        .IsUnique()
                        .HasFilter("status = 0");

                    b.HasIndex("DiscountProgramId");

                    b.HasIndex("Status");

                    b.ToTable("passenger_discounts", (string)null);
                });

            modelBuilder.Entity("TransitPay.API.Models.QRCode", b =>
                {
                    b.Property<int>("QRCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("qr_code_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QRCodeId"));

                    b.Property<int>("CardId")
                        .HasColumnType("integer")
                        .HasColumnName("card_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("QRCodeId");

                    b.HasIndex("CardId")
                        .IsUnique();

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("CardId", "IsActive")
                        .IsUnique()
                        .HasFilter("is_active = true");

                    b.ToTable("qr_codes", (string)null);
                });

            modelBuilder.Entity("TransitPay.API.Models.RefreshToken", b =>
                {
                    b.Property<int>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("token_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TokenId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int?>("ReplacedByTokenId")
                        .HasColumnType("integer")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean")
                        .HasColumnName("revoked");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("TokenId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId", "Token");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("TransitPay.API.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("RoleName")
                        .HasColumnType("integer")
                        .HasColumnName("role_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("RoleId");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("TransitPay.API.Models.Terminal", b =>
                {
                    b.Property<int>("TerminalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("terminal_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TerminalId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("TerminalName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("terminal_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TerminalId");

                    b.HasIndex("TerminalName")
                        .IsUnique()
                        .HasFilter("terminal_name IS NOT NULL AND terminal_name <> ''");

                    b.ToTable("terminals", (string)null);
                });

            modelBuilder.Entity("TransitPay.API.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("transaction_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TransactionId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<int?>("CardId")
                        .HasColumnType("integer")
                        .HasColumnName("card_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DestinationTerminalName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("destination_terminal_name");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("discount_amount");

                    b.Property<decimal?>("DiscountPercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("discount_percentage");

                    b.Property<int?>("DiscountTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("discount_type_id");

                    b.Property<int?>("DriverId")
                        .HasColumnType("integer")
                        .HasColumnName("driver_id");

                    b.Property<int?>("FareId")
                        .HasColumnType("integer")
                        .HasColumnName("fare_id");

                    b.Property<decimal>("FinalFare")
                        .HasColumnType("numeric")
                        .HasColumnName("final_fare");

                    b.Property<int?>("OriginTerminalId")
                        .HasColumnType("integer")
                        .HasColumnName("origin_terminal_id");

                    b.Property<string>("OriginTerminalName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("origin_terminal_name");

                    b.Property<string>("PaymentMode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payment_mode");

                    b.Property<string>("PaymentRequestKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("payment_request_key");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("text")
                        .HasColumnName("reference_number");

                    b.Property<decimal>("RegularFare")
                        .HasColumnType("numeric")
                        .HasColumnName("regular_fare");

                    b.Property<decimal>("RemainingBalance")
                        .HasColumnType("numeric")
                        .HasColumnName("remaining_balance");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int?>("TerminalId")
                        .HasColumnType("integer")
                        .HasColumnName("terminal_id");

                    b.Property<string>("TransactionName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("transaction_name");

                    b.Property<string>("TransactionReferenceNumber")
                        .HasColumnType("text")
                        .HasColumnName("transaction_reference_number");

                    b.Property<int>("TransactionType")
                        .HasColumnType("integer")
                        .HasColumnName("transaction_type");

                    b.Property<int?>("TripId")
                        .HasColumnType("integer")
                        .HasColumnName("trip_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TransactionId");

                    b.HasIndex("CardId");

                    b.HasIndex("DiscountTypeId");

                    b.HasIndex("DriverId");

                    b.HasIndex("FareId");

                    b.HasIndex("OriginTerminalId");

                    b.HasIndex("PaymentRequestKey")
                        .IsUnique()
                        .HasFilter("payment_request_key IS NOT NULL AND status = 1");

                    b.HasIndex("ReferenceNumber")
                        .IsUnique()
                        .HasFilter("reference_number IS NOT NULL AND reference_number <> ''");

                    b.HasIndex("Status");

                    b.HasIndex("TerminalId");

                    b.HasIndex("TransactionReferenceNumber")
                        .IsUnique()
                        .HasFilter("transaction_reference_number IS NOT NULL");

                    b.HasIndex("TransactionType");

                    b.HasIndex("TripId");

                    b.HasIndex("CardId", "CreatedAt")
                        .IsDescending(false, true);

                    b.ToTable("transactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_transactions_amount_non_negative", "\"amount\" >= 0");

                            t.HasCheckConstraint("CK_transactions_discount_amount_non_negative", "\"discount_amount\" IS NULL OR \"discount_amount\" >= 0");

                            t.HasCheckConstraint("CK_transactions_discount_percentage_range", "\"discount_percentage\" IS NULL OR (\"discount_percentage\" >= 0 AND \"discount_percentage\" <= 100)");

                            t.HasCheckConstraint("CK_transactions_final_fare_non_negative", "\"final_fare\" >= 0");

                            t.HasCheckConstraint("CK_transactions_regular_fare_non_negative", "\"regular_fare\" >= 0");
                        });
                });

            modelBuilder.Entity("TransitPay.API.Models.Trip", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("trip_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TripId"));

                    b.Property<DateTime?>("BoardingOriginUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("boarding_origin_updated_at");

                    b.Property<int?>("BusId")
                        .HasColumnType("integer")
                        .HasColumnName("bus_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CurrentBoardingOriginTerminalId")
                        .HasColumnType("integer")
                        .HasColumnName("current_boarding_origin_terminal_id");

                    b.Property<int>("DriverId")
                        .HasColumnType("integer")
                        .HasColumnName("driver_id");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<int?>("FinalDestinationTerminalId")
                        .HasColumnType("integer")
                        .HasColumnName("final_destination_terminal_id");

                    b.Property<int?>("OriginTerminalId")
                        .HasColumnType("integer")
                        .HasColumnName("origin_terminal_id");

                    b.Property<int>("PassengerCount")
                        .HasColumnType("integer")
                        .HasColumnName("passenger_count");

                    b.Property<string>("RouteName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("route_name");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<decimal>("TotalRevenue")
                        .HasColumnType("numeric")
                        .HasColumnName("total_revenue");

                    b.Property<int>("TripStatus")
                        .HasColumnType("integer")
                        .HasColumnName("trip_status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TripId");

                    b.HasIndex("CurrentBoardingOriginTerminalId");

                    b.HasIndex("DriverId")
                        .IsUnique()
                        .HasFilter("trip_status = 1");

                    b.HasIndex("EndedAt");

                    b.HasIndex("FinalDestinationTerminalId");

                    b.HasIndex("OriginTerminalId");

                    b.HasIndex("StartedAt");

                    b.HasIndex("TripStatus");

                    b.HasIndex("DriverId", "TripStatus");

                    b.ToTable("trips", (string)null);
                });

            modelBuilder.Entity("TransitPay.API.Models.TripPlan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("plan_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlanId"));

                    b.Property<int>("CardId")
                        .HasColumnType("integer")
                        .HasColumnName("card_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DestinationTerminalId")
                        .HasColumnType("integer")
                        .HasColumnName("destination_terminal_id");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("discount_amount");

                    b.Property<decimal?>("DiscountPercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("discount_percentage");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<decimal>("FinalFarePrice")
                        .HasColumnType("numeric")
                        .HasColumnName("final_fare_price");

                    b.Property<decimal>("NormalFare")
                        .HasColumnType("numeric")
                        .HasColumnName("normal_fare");

                    b.Property<int>("OriginTerminalId")
                        .HasColumnType("integer")
                        .HasColumnName("origin_terminal_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("PlanId");

                    b.HasIndex("CardId");

                    b.HasIndex("DestinationTerminalId");

                    b.HasIndex("OriginTerminalId");

                    b.HasIndex("UserId");

                    b.ToTable("trip_plans", (string)null);
                });

            modelBuilder.Entity("TransitPay.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_attempts");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mobile_number");

                    b.Property<DateTime?>("PasswordChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_changed_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PlateNumber")
                        .HasColumnType("text")
                        .HasColumnName("plate_number");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.HasIndex("MobileNumber")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TransitPay.API.Models.Wallet", b =>
                {
                    b.Property<int>("WalletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("wallet_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WalletId"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric")
                        .HasColumnName("balance");

                    b.Property<int>("CardId")
                        .HasColumnType("integer")
                        .HasColumnName("card_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("WalletId");

                    b.HasIndex("CardId")
                        .IsUnique();

                    b.ToTable("wallets", null, t =>
                        {
                            t.HasCheckConstraint("CK_wallets_balance_non_negative", "\"balance\" >= 0");
                        });
                });

            modelBuilder.Entity("TransitPay.API.Models.Card", b =>
                {
                    b.HasOne("TransitPay.API.Models.User", "User")
                        .WithMany("Cards")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TransitPay.API.Models.DiscountApplication", b =>
                {
                    b.HasOne("TransitPay.API.Models.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TransitPay.API.Models.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransitPay.API.Models.DiscountProgram", "DiscountProgram")
                        .WithMany("DiscountApplications")
                        .HasForeignKey("DiscountProgramId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TransitPay.API.Models.DiscountType", "DiscountType")
                        .WithMany("DiscountApplications")
                        .HasForeignKey("DiscountTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransitPay.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedByUser");

                    b.Navigation("Card");

                    b.Navigation("DiscountProgram");

                    b.Navigation("DiscountType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TransitPay.API.Models.DiscountProgram", b =>
                {
                    b.HasOne("TransitPay.API.Models.DiscountType", "DiscountType")
                        .WithMany()
                        .HasForeignKey("DiscountTypeId");

                    b.Navigation("DiscountType");
                });

            modelBuilder.Entity("TransitPay.API.Models.FareRule", b =>
                {
                    b.HasOne("TransitPay.API.Models.Terminal", "DestinationTerminal")
                        .WithMany()
                        .HasForeignKey("DestinationTerminalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransitPay.API.Models.Terminal", "OriginTerminal")
                        .WithMany()
                        .HasForeignKey("OriginTerminalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DestinationTerminal");

                    b.Navigation("OriginTerminal");
                });

            modelBuilder.Entity("TransitPay.API.Models.PassengerDiscount", b =>
                {
                    b.HasOne("TransitPay.API.Models.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TransitPay.API.Models.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransitPay.API.Models.DiscountProgram", "DiscountProgram")
                        .WithMany()
                        .HasForeignKey("DiscountProgramId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApprovedByUser");

                    b.Navigation("Card");

                    b.Navigation("DiscountProgram");
                });

            modelBuilder.Entity("TransitPay.API.Models.QRCode", b =>
                {
                    b.HasOne("TransitPay.API.Models.Card", "Card")
                        .WithOne("QRCode")
                        .HasForeignKey("TransitPay.API.Models.QRCode", "CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("TransitPay.API.Models.RefreshToken", b =>
                {
                    b.HasOne("TransitPay.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TransitPay.API.Models.Transaction", b =>
                {
                    b.HasOne("TransitPay.API.Models.Card", "Card")
                        .WithMany("Transactions")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TransitPay.API.Models.DiscountType", "DiscountType")
                        .WithMany()
                        .HasForeignKey("DiscountTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TransitPay.API.Models.User", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TransitPay.API.Models.FareRule", "FareRule")
                        .WithMany()
                        .HasForeignKey("FareId");

                    b.HasOne("TransitPay.API.Models.Terminal", "OriginTerminal")
                        .WithMany()
                        .HasForeignKey("OriginTerminalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TransitPay.API.Models.Terminal", "Terminal")
                        .WithMany()
                        .HasForeignKey("TerminalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TransitPay.API.Models.Trip", "Trip")
                        .WithMany("Transactions")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Card");

                    b.Navigation("DiscountType");

                    b.Navigation("Driver");

                    b.Navigation("FareRule");

                    b.Navigation("OriginTerminal");

                    b.Navigation("Terminal");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TransitPay.API.Models.Trip", b =>
                {
                    b.HasOne("TransitPay.API.Models.Terminal", "CurrentBoardingOriginTerminal")
                        .WithMany()
                        .HasForeignKey("CurrentBoardingOriginTerminalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TransitPay.API.Models.User", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransitPay.API.Models.Terminal", "FinalDestinationTerminal")
                        .WithMany()
                        .HasForeignKey("FinalDestinationTerminalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TransitPay.API.Models.Terminal", "OriginTerminal")
                        .WithMany()
                        .HasForeignKey("OriginTerminalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CurrentBoardingOriginTerminal");

                    b.Navigation("Driver");

                    b.Navigation("FinalDestinationTerminal");

                    b.Navigation("OriginTerminal");
                });

            modelBuilder.Entity("TransitPay.API.Models.TripPlan", b =>
                {
                    b.HasOne("TransitPay.API.Models.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TransitPay.API.Models.Terminal", "DestinationTerminal")
                        .WithMany()
                        .HasForeignKey("DestinationTerminalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TransitPay.API.Models.Terminal", "OriginTerminal")
                        .WithMany()
                        .HasForeignKey("OriginTerminalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TransitPay.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("DestinationTerminal");

                    b.Navigation("OriginTerminal");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TransitPay.API.Models.User", b =>
                {
                    b.HasOne("TransitPay.API.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TransitPay.API.Models.Wallet", b =>
                {
                    b.HasOne("TransitPay.API.Models.Card", "Card")
                        .WithOne("Wallet")
                        .HasForeignKey("TransitPay.API.Models.Wallet", "CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("TransitPay.API.Models.Card", b =>
                {
                    b.Navigation("QRCode");

                    b.Navigation("Transactions");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("TransitPay.API.Models.DiscountProgram", b =>
                {
                    b.Navigation("DiscountApplications");
                });

            modelBuilder.Entity("TransitPay.API.Models.DiscountType", b =>
                {
                    b.Navigation("DiscountApplications");
                });

            modelBuilder.Entity("TransitPay.API.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TransitPay.API.Models.Trip", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("TransitPay.API.Models.User", b =>
                {
                    b.Navigation("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
