// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TransitPay.API.Data;

#nullable disable

namespace TransitPay.API.Migrations
{
    [DbContext(typeof(TransitPayDbContext))]
    partial class TransitPayDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TransitPay.API.Models.Card", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("card_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CardId"));

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("card_number");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiry_date");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issue_date");

                    b.Property<int>("PassengerType")
                        .HasColumnType("integer")
                        .HasColumnName("passenger_type");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("CardId");

                    b.HasIndex("CardNumber")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("cards", (string)null);
                });

            modelBuilder.Entity("TransitPay.API.Models.FareRule", b =>
                {
                    b.Property<int>("FareId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("fare_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FareId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("DestinationStationId")
                        .HasColumnType("integer")
                        .HasColumnName("destination_station_id");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_date");

                    b.Property<decimal>("FareAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("fare_amount");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("OriginStationId")
                        .HasColumnType("integer")
                        .HasColumnName("origin_station_id");

                    b.Property<int>("PassengerType")
                        .HasColumnType("integer")
                        .HasColumnName("passenger_type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("VehicleType")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_type");

                    b.HasKey("FareId");

                    b.HasIndex("DestinationStationId");

                    b.HasIndex("OriginStationId", "DestinationStationId", "VehicleType", "PassengerType")
                        .IsUnique()
                        .HasFilter("is_active = true AND deleted_at IS NULL");

                    b.ToTable("fare_rules", (string)null);
                });

            modelBuilder.Entity("TransitPay.API.Models.PaymentSession", b =>
                {
                    b.Property<Guid>("PaymentSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("payment_session_id");

                    b.Property<int>("CardId")
                        .HasColumnType("integer")
                        .HasColumnName("card_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DestinationStationId")
                        .HasColumnType("integer")
                        .HasColumnName("destination_station_id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<decimal>("Fare")
                        .HasColumnType("numeric")
                        .HasColumnName("fare");

                    b.Property<int>("OriginStationId")
                        .HasColumnType("integer")
                        .HasColumnName("origin_station_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("PaymentSessionId");

                    b.HasIndex("CardId")
                        .IsUnique()
                        .HasFilter("status IN (0, 1, 2)");

                    b.HasIndex("DestinationStationId");

                    b.HasIndex("OriginStationId");

                    b.HasIndex("UserId");

                    b.ToTable("payment_sessions", (string)null);
                });

            modelBuilder.Entity("TransitPay.API.Models.QRCode", b =>
                {
                    b.Property<int>("QRCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("qr_code_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QRCodeId"));

                    b.Property<int>("CardId")
                        .HasColumnType("integer")
                        .HasColumnName("card_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("QRCodeId");

                    b.HasIndex("CardId")
                        .IsUnique();

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("CardId", "IsActive")
                        .IsUnique()
                        .HasFilter("is_active = true");

                    b.ToTable("qr_codes", (string)null);
                });

            modelBuilder.Entity("TransitPay.API.Models.RefreshToken", b =>
                {
                    b.Property<int>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("token_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TokenId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean")
                        .HasColumnName("revoked");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("TokenId");

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("TransitPay.API.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("RoleName")
                        .HasColumnType("integer")
                        .HasColumnName("role_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("RoleId");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("TransitPay.API.Models.Station", b =>
                {
                    b.Property<int>("StationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("station_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("station_name");

                    b.Property<int>("TownId")
                        .HasColumnType("integer")
                        .HasColumnName("town_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("StationId");

                    b.HasIndex("TownId");

                    b.ToTable("stations", (string)null);
                });

            modelBuilder.Entity("TransitPay.API.Models.Town", b =>
                {
                    b.Property<int>("TownId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("town_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TownId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("TownName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("town_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TownId");

                    b.ToTable("towns", (string)null);
                });

            modelBuilder.Entity("TransitPay.API.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("transaction_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TransactionId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<int?>("CardId")
                        .HasColumnType("integer")
                        .HasColumnName("card_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("DriverId")
                        .HasColumnType("integer")
                        .HasColumnName("driver_id");

                    b.Property<int?>("FareId")
                        .HasColumnType("integer")
                        .HasColumnName("fare_id");

                    b.Property<int?>("OriginStationId")
                        .HasColumnType("integer")
                        .HasColumnName("origin_station_id");

                    b.Property<Guid?>("PaymentSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_session_id");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("text")
                        .HasColumnName("reference_number");

                    b.Property<int?>("StationId")
                        .HasColumnType("integer")
                        .HasColumnName("station_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TransactionName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("transaction_name");

                    b.Property<string>("TransactionReferenceNumber")
                        .HasColumnType("text")
                        .HasColumnName("transaction_reference_number");

                    b.Property<int>("TransactionType")
                        .HasColumnType("integer")
                        .HasColumnName("transaction_type");

                    b.Property<int?>("TripId")
                        .HasColumnType("integer")
                        .HasColumnName("trip_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TransactionId");

                    b.HasIndex("CardId");

                    b.HasIndex("DriverId");

                    b.HasIndex("FareId");

                    b.HasIndex("OriginStationId");

                    b.HasIndex("PaymentSessionId");

                    b.HasIndex("StationId");

                    b.HasIndex("TransactionReferenceNumber")
                        .IsUnique()
                        .HasFilter("transaction_reference_number IS NOT NULL");

                    b.HasIndex("TripId");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("TransitPay.API.Models.Trip", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("trip_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TripId"));

                    b.Property<int?>("BusId")
                        .HasColumnType("integer")
                        .HasColumnName("bus_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DriverId")
                        .HasColumnType("integer")
                        .HasColumnName("driver_id");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<int>("FinalDestinationStationId")
                        .HasColumnType("integer")
                        .HasColumnName("final_destination_station_id");

                    b.Property<int>("OriginStationId")
                        .HasColumnType("integer")
                        .HasColumnName("origin_station_id");

                    b.Property<int>("PassengerCount")
                        .HasColumnType("integer")
                        .HasColumnName("passenger_count");

                    b.Property<string>("RouteName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("route_name");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<decimal>("TotalRevenue")
                        .HasColumnType("numeric")
                        .HasColumnName("total_revenue");

                    b.Property<int>("TripStatus")
                        .HasColumnType("integer")
                        .HasColumnName("trip_status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TripId");

                    b.HasIndex("DriverId")
                        .IsUnique()
                        .HasFilter("trip_status = 1");

                    b.HasIndex("FinalDestinationStationId");

                    b.HasIndex("OriginStationId");

                    b.ToTable("trips", (string)null);
                });

            modelBuilder.Entity("TransitPay.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mobile_number");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.HasIndex("MobileNumber")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TransitPay.API.Models.Wallet", b =>
                {
                    b.Property<int>("WalletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("wallet_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WalletId"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric")
                        .HasColumnName("balance");

                    b.Property<int>("CardId")
                        .HasColumnType("integer")
                        .HasColumnName("card_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("WalletId");

                    b.HasIndex("CardId")
                        .IsUnique();

                    b.ToTable("wallets", (string)null);
                });

            modelBuilder.Entity("TransitPay.API.Models.Card", b =>
                {
                    b.HasOne("TransitPay.API.Models.User", "User")
                        .WithMany("Cards")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TransitPay.API.Models.FareRule", b =>
                {
                    b.HasOne("TransitPay.API.Models.Station", "DestinationStation")
                        .WithMany()
                        .HasForeignKey("DestinationStationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransitPay.API.Models.Station", "OriginStation")
                        .WithMany()
                        .HasForeignKey("OriginStationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DestinationStation");

                    b.Navigation("OriginStation");
                });

            modelBuilder.Entity("TransitPay.API.Models.PaymentSession", b =>
                {
                    b.HasOne("TransitPay.API.Models.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransitPay.API.Models.Station", "DestinationStation")
                        .WithMany()
                        .HasForeignKey("DestinationStationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransitPay.API.Models.Station", "OriginStation")
                        .WithMany()
                        .HasForeignKey("OriginStationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransitPay.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("DestinationStation");

                    b.Navigation("OriginStation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TransitPay.API.Models.QRCode", b =>
                {
                    b.HasOne("TransitPay.API.Models.Card", "Card")
                        .WithOne("QRCode")
                        .HasForeignKey("TransitPay.API.Models.QRCode", "CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("TransitPay.API.Models.RefreshToken", b =>
                {
                    b.HasOne("TransitPay.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TransitPay.API.Models.Station", b =>
                {
                    b.HasOne("TransitPay.API.Models.Town", "Town")
                        .WithMany("Stations")
                        .HasForeignKey("TownId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Town");
                });

            modelBuilder.Entity("TransitPay.API.Models.Transaction", b =>
                {
                    b.HasOne("TransitPay.API.Models.Card", "Card")
                        .WithMany("Transactions")
                        .HasForeignKey("CardId");

                    b.HasOne("TransitPay.API.Models.User", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TransitPay.API.Models.FareRule", "FareRule")
                        .WithMany()
                        .HasForeignKey("FareId");

                    b.HasOne("TransitPay.API.Models.Station", "OriginStation")
                        .WithMany()
                        .HasForeignKey("OriginStationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TransitPay.API.Models.PaymentSession", "PaymentSession")
                        .WithMany()
                        .HasForeignKey("PaymentSessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TransitPay.API.Models.Station", "Station")
                        .WithMany("Transactions")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TransitPay.API.Models.Trip", "Trip")
                        .WithMany("Transactions")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Card");

                    b.Navigation("Driver");

                    b.Navigation("FareRule");

                    b.Navigation("OriginStation");

                    b.Navigation("PaymentSession");

                    b.Navigation("Station");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TransitPay.API.Models.Trip", b =>
                {
                    b.HasOne("TransitPay.API.Models.User", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransitPay.API.Models.Station", "FinalDestinationStation")
                        .WithMany()
                        .HasForeignKey("FinalDestinationStationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransitPay.API.Models.Station", "OriginStation")
                        .WithMany()
                        .HasForeignKey("OriginStationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("FinalDestinationStation");

                    b.Navigation("OriginStation");
                });

            modelBuilder.Entity("TransitPay.API.Models.User", b =>
                {
                    b.HasOne("TransitPay.API.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TransitPay.API.Models.Wallet", b =>
                {
                    b.HasOne("TransitPay.API.Models.Card", "Card")
                        .WithOne("Wallet")
                        .HasForeignKey("TransitPay.API.Models.Wallet", "CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("TransitPay.API.Models.Card", b =>
                {
                    b.Navigation("QRCode");

                    b.Navigation("Transactions");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("TransitPay.API.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TransitPay.API.Models.Station", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("TransitPay.API.Models.Town", b =>
                {
                    b.Navigation("Stations");
                });

            modelBuilder.Entity("TransitPay.API.Models.Trip", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("TransitPay.API.Models.User", b =>
                {
                    b.Navigation("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
